name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 07:00 AM ICT

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-solutions
          verbose: true
          commit-header: '[LeetCode Sync]'
          commit-author: "Khánh Tâm Phạm"
          commit-author-email: "84433497+AI-WFox@users.noreply.github.com"
